apiVersion: v1
kind: Service
metadata:
  name: access-vw
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "access-vw.labels" . | nindent 4 }}
spec:
  selector:
    app: access-vw
  ports:
    - port: {{ .Values.server.securePort }}
      targetPort: {{ .Values.server.securePort }}
      name: https
