apiVersion: operator.kcp.io/v1alpha1
kind: Kubeconfig
metadata:
  name: mcp-vw-kubeconfig
  namespace: kcp-system
spec:
  username: mcp-virtual-workspace
  groups:
    - mcp-virtual-workspace
  validity: 8766h # 1 year
  secretRef:
    name: mcp-vw-kubeconfig
  target:
    rootShardRef:
      name: root
